### PR TITLE
Fixed some missed data binding annotations in global config

### PR DESCRIPTION
**Pull request by rsandell**
It didn't seem to matter, at least for JCasC, but something must have not worked properly.

### CODE REVIEW

**Comment by NKJensen** [comment]
Could this change fix https://issues.jenkins-ci.org/browse/JENKINS-59204 ?

**Comment by rsandell** [comment]
@NKJensen Not likely
The claim plugin needs to change [how it finds BFA's PluginImpl](https://github.com/jenkinsci/claim-plugin/blob/master/src/main/java/hudson/plugins/claim/ClaimBuildFailureAnalyzer.java#L46) as it is now a GlobalConfiguration instead of a Plugin class

**Comment by rsandell** [comment]
Had I known that the claim plugin used that much of BFA's PluginImpl interface I would probably not had merged the JCasC compatibility as it was implemented, but the Plugin interface is deprecated since many years so I didn't think it would be an issue.

**Comment by timja** [comment]
> Had I known that the claim plugin used that much of BFA's PluginImpl interface I would probably not had merged the JCasC compatibility as it was implemented, but the Plugin interface is deprecated since many years so I didn't think it would be an issue.

I'll try take a look at fixing it next week

**Comment by timja** [comment]
@NKJensen these PRs will fix it:
https://github.com/jenkinsci/build-failure-analyzer-plugin/pull/119
https://github.com/jenkinsci/claim-plugin/pull/62

**Comment by NKJensen** [comment]
On 2019-11-05 08:59, Tim Jacomb wrote:

> @NKJensen [1] these PRs will fix it:
> #119 [2]
> jenkinsci/claim-plugin#62 [3] 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [4], or unsubscribe [5].

Thank you very much, Tim. 

I'm not used to the Jenkins work flow, so I am a bit unsure about how to
read the comments on the latter PR (pull request?) - does it pass the
test now? 

https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fclaim-plugin/detail/PR-62/1/pipeline


The first PR seems to be all fine (green) 

I'll see if I can figure out how to test the change on our site. 

Once again, many thanks for looking into this matter :-) 

Best regards,  

Niels Kristian 

------------------------------------------
Spejd er sejt!

Det Danske Spejderkorps
------------------------------------------
 

Links:
------
[1] https://github.com/NKJensen
[2] https://github.com/jenkinsci/build-failure-analyzer-plugin/pull/119
[3] https://github.com/jenkinsci/claim-plugin/pull/62
[4]
https://github.com/jenkinsci/build-failure-analyzer-plugin/pull/118?email_source=notifications&amp;email_token=AAPGVQKMYEMF3DLKIJNBFULQSERX7A5CNFSM4JFHDLEKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDB5YHA#issuecomment-549706780
[5]

**Comment by timja** [comment]
@NKJensen you can get the RC here:
https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/claim/2.16-rc427.3dca5a998b0b/

I had  to wait for the bfa build to pass before I could link the builds together with an 'incremental' version

**Comment by NKJensen** [comment]
On 2019-11-05 09:45, Tim Jacomb wrote:

> @NKJensen [1] you can get the RC here:
> https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/claim/2.16-rc427.3dca5a998b0b/ 
> 
> I had to wait for the bfa build to pass before I could link the builds together with an 'incremental' version 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].

Sure, we will run it on our QA server.

------------------------------------------
Spejd er sejt!

Det Danske Spejderkorps
------------------------------------------
 

Links:
------
[1] https://github.com/NKJensen
[2]
https://github.com/jenkinsci/build-failure-analyzer-plugin/pull/118?email_source=notifications&amp;email_token=AAPGVQOKIFIZNAWLTJQOFA3QSEXD3A5CNFSM4JFHDLEKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDCBO7Q#issuecomment-549721982
[3]

**Pull request merged**
