### PR TITLE
fix jcasc test harness

### PR DESCRIPTION
**Pull request by casz**
JCasc had to create a new dependency that wasn't a tests classifier because maven doesn't allow you to bring dependencies through classifiers.

Upgrading here so that PCT works again,

Tracking:
jenkinsci/bom#164

Note: We'll need a release for PCT please

### CODE REVIEW

**Comment by timja** [comment]
Lots of enforcer failures

**Comment by casz** [comment]
Well all related to jackson2-api it seems

**Comment by rsandell** [comment]
Tickling the PR builder now that #125 is merged

**Comment by rsandell** [comment]
@casz still some enforcer rules complaining.

**Comment by casz** [comment]
Thanks @rsandell I'll look into it.

**Pull request merged**
