### PR TITLE
DOC: Add Issues, Plugin main page URL to Readme.txt; Regex Question.

### PR DESCRIPTION
**Pull request by AnneTheAgile**
Another test to see if PR's are accepted :). I had a hard time navigating without these urls.

### CODE REVIEW

**Comment by AnneTheAgile** [comment]
I came here because I cannot get my second failure case to match. I've simplified it down to the string
````
MSB5012
````
which I'm thinking should clearly match in any regex parser. I would prefer to match; 
````
error MSB5012: Unexpected end-of-file reached inside ".nuget" project section.
````
but I'm not sure which characters need to be escaped and how. 

So,  with the one word item, it won't match, yet at the end of my build, I have; 
````
"=====================Section-Hdr============ 1.Github Checkout Done. 2.Start Build SLN." 
"=====================Section-Hdr============ 1.Github Checkout Done. 2.Start Build SLN."

C:\Program Files (x86)\Jenkins\jobs\higgens-master\workspace>exit 0 
Path To MSBuild.exe: c:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe
Executing the command cmd.exe /C " c:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe /p:Configuration=Debug "C:\Program Files (x86)\Jenkins\jobs\higgens-master\workspace\Higgens.sln" " && exit %%ERRORLEVEL%% from C:\Program Files (x86)\Jenkins\jobs\higgens-master\workspace
[workspace] $ cmd.exe /C " c:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe /p:Configuration=Debug "C:\Program Files (x86)\Jenkins\jobs\higgens-master\workspace\Higgens.sln" " && exit %%ERRORLEVEL%%
Microsoft (R) Build Engine version 4.0.30319.18408
[Microsoft .NET Framework, version 4.0.30319.18444]
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 1/6/2015 3:14:38 PM.
C:\Program Files (x86)\Jenkins\jobs\higgens-master\workspace\Higgens.sln : Solution file error MSB5012: Unexpected end-of-file reached inside ".nuget" project section.

Build FAILED.

  C:\Program Files (x86)\Jenkins\jobs\higgens-master\workspace\Higgens.sln : Solution file error MSB5012: Unexpected end-of-file reached inside ".nuget" project section.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.11
Build step 'Build a Visual Studio project or solution using MSBuild' marked build as failure
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Finished: FAILURE
````
Ideas? Help? thank you!

**Comment by rsandell** [comment]
The plugin wiki page is the central hub for all plugins, from there everything is linked.
The wiki page is also stated in the pom file. Same as for almost all Jenkins plugins.

**Comment by rsandell** [comment]
The java regexp docs are here http://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html it should be linked from the help docs in the plugin I think.

**Comment by AnneTheAgile** [comment]
ty @rsandell ! Yes, I know that there are other places for these links, but imho they should be here, too, otherwise searching from Google gets to be more roundabout than required. I wrote this in response to my troubles finding #29 , for example.

Also it seems like a trivial change, so I hope you can accept it?

I will check out the regexp, ty!

**Pull request merged**
