### PR TITLE
Require Java 17 and 2.475; adapt test suite to EE 9

### PR DESCRIPTION
**Pull request by basil**
Subsumes #181. Allow this plugin's test suite to be exercised regularly in Plugin Compatibility Tester (PCT) in https://github.com/jenkinsci/bom by requiring Java 17 or newer and Jenkins 2.475 (released today) or newer.

This PR goes against the usual advice from https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/ by requiring a weekly release. The advantage is that this will allow plugin compatibility testing (PCT). The disadvantage is that new features and bug fixes can't be released to LTS users for another few months.

The choice is up to the maintainer as to whether or not to accept this PR. If this PR is rejected, we will stop testing this plugin in PCT.

### CODE REVIEW

**Comment by basil** [comment]
Should fix [JENKINS-73903](https://issues.jenkins.io/browse/JENKINS-73903), I think.

**Comment by TWestling** [comment]
@basil 
Regarding the dependency on a weekly release: Is the reason that we don't have an LTS with the requirements on Spring 6 and EE 9, and that we can go back to LTS depedency later on, once it is stabilized?

**Comment by basil** [comment]
@TWestling Yes exactly. When 2.479.1 LTS is released on October 30, I will file another PR in this repository to move back to the LTS line.

**Review by TWestling — APPROVED** [review]

**Comment by TWestling** [comment]
@basil My plan was to release it now, thought I'd try it out first, and when running hpi:run, I get:
java.lang.ClassNotFoundException: jakarta.servlet.ServletContextListener

Any idea why? Running on Maven 3.9.8 and JDK 17.

**Comment by TWestling** [comment]
Managed to test this in a roundabout way, so the plugin is now released.
Still need some help on running hpi:run with the jakarta changes though, thankful for any help.

**Comment by basil** [comment]
I will file a PR next Wednesday when 2.479.1 is released that will clean up the parent POM, switch back to LTS, and restore `hpi:run`. Thanks for your patience as we go through this rough migration.

**Comment by basil** [comment]
> I will file a PR next Wednesday when 2.479.1 is released that will clean up the parent POM, switch back to LTS, and restore `hpi:run`.

Done in #183

**Pull request merged**
