### PR TITLE
Integration with the Metrics plugin

### PR DESCRIPTION
**Pull request by jamesrobson-secondmind**
This adds integration with the Metrics plugin to replace the graphs that were removed by version 2, this will allow users to integrate with there own metrics systems (e.g. Prometheus or Data Dog).
This uses a counter from the Metrics library which will reset when jenkins is restarted which was done for implementation simplicity.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by malashi** [comment]
can this be merged now?

**Comment by jamesrobson-secondmind** [comment]
Yes, this is ready to merge now.

**Review by rsandell — APPROVED** [review]

**Comment by PayBas** [comment]
I feel that there is a big omission here: the "Fallback categories"
image

**Comment by jamesrobson-secondmind** [comment]
#148 fixes the fallback categories

**Pull request merged**
