### PR TITLE
JENKINS-42755 Missing pipeline logs

### PR DESCRIPTION
**Pull request by timja**
https://issues.jenkins-ci.org/browse/JENKINS-42755

Note this does get this on newer jenkins:
```
2019-06-02 10:46:55.548+0000 [id=59]	WARNING	o.j.p.workflow.job.WorkflowRun#getLogFile: Avoid calling getLogFile on test #2
java.lang.UnsupportedOperationException
```
It's covered in JENKINS-54840, there's a few places in the plugin that need updates.

In this case I haven't been able to find a way to append to a build file currently when it's not a log file on disk...

One option would be to not log to the build file anymore...

### CODE REVIEW

**Comment by rsandell** [comment]
Have you checked that this doesn't mess with the tokenizer and sending emails? I think it might.

**Comment by timja** [comment]
not sure... will take a look.

**Comment by rsandell** [comment]
If it is, or if it's hard to verify, maybe keep `onCompleted` for all `AbstractBuild`s and only use `onFinalized` for any non `Abstractbuild`s
The tokenizer is not working for pipelines anyway since the emailing is done inside the build before the BFA has had a chance to run as it is, so we won't "break" anything that isn't already broken ;).

**Comment by timja** [comment]
that sounds like the easiest solution 👍

**Comment by timja** [comment]
I've made AbstractBuild continue to use completed, I don't use the functionality you mentioned and don't really know how to test it.

I've tested free style and pipeline, both are working as expected.
image

image

**Comment by timja** [comment]
done

**Pull request merged**
